# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-1.3838e-01,  8.2957e-43, -1.3838e-01],
        [ 8.2957e-43, -1.3838e-01,  8.2957e-43],
        [-1.3838e-01,  8.2957e-43, -1.3838e-01],
        [ 8.2957e-43, -1.3838e-01,  8.2957e-43],
        [-1.3838e-01,  8.2957e-43, -1.3838e-01]])


Construct a randomly initialized matrix

In [11]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4885, 0.9907, 0.2911],
        [0.7310, 0.0848, 0.0046],
        [0.9029, 0.6800, 0.8854],
        [0.6106, 0.1693, 0.1537],
        [0.7217, 0.1609, 0.6773]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.5473, 0.7614, 0.0255],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.3605, 0.9909, 0.7613],
        [0.4835, 0.0216, 0.3114]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
x = torch.Tensor(2,17)
x.size()

torch.Size([2, 17])

In [7]:
x = torch.FloatTensor(3,1)
x.dtype

torch.float32

In [8]:
x = torch.LongTensor(5,2,1) # makes it li
x[:] = 7
x

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [9]:
x = torch.ByteTensor(5)
x[1:4] = 1
x

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.4344, 1.2168, 0.2990],
        [1.3449, 0.6535, 0.4929],
        [0.9215, 1.4273, 1.8680],
        [1.5696, 0.7409, 0.3731],
        [0.8908, 1.1131, 1.3687]])


### 2.2 Addition: syntax 2

In [13]:
print(torch.add(x, y))

tensor([[1.4344, 1.2168, 0.2990],
        [1.3449, 0.6535, 0.4929],
        [0.9215, 1.4273, 1.8680],
        [1.5696, 0.7409, 0.3731],
        [0.8908, 1.1131, 1.3687]])


### 2.3 Addition: giving an output tensor

In [14]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.4344, 1.2168, 0.2990],
        [1.3449, 0.6535, 0.4929],
        [0.9215, 1.4273, 1.8680],
        [1.5696, 0.7409, 0.3731],
        [0.8908, 1.1131, 1.3687]])


### 2.4 Addition: in-place

adds `x`to `y`

In [15]:
y.add_(x)
print(y)

tensor([[1.4344, 1.2168, 0.2990],
        [1.3449, 0.6535, 0.4929],
        [0.9215, 1.4273, 1.8680],
        [1.5696, 0.7409, 0.3731],
        [0.8908, 1.1131, 1.3687]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [16]:
print(x[:, 1])

tensor([0.9907, 0.0848, 0.6800, 0.1693, 0.1609])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [20]:
torch.Tensor.mul(x,y)

tensor([[0.7007, 1.2055, 0.0870],
        [0.9831, 0.0554, 0.0023],
        [0.8320, 0.9706, 1.6539],
        [0.9584, 0.1254, 0.0573],
        [0.6429, 0.1791, 0.9270]])

In [21]:
x.mul_(y)

tensor([[0.7007, 1.2055, 0.0870],
        [0.9831, 0.0554, 0.0023],
        [0.8320, 0.9706, 1.6539],
        [0.9584, 0.1254, 0.0573],
        [0.6429, 0.1791, 0.9270]])

In [23]:
torch.Tensor.div(x,y)

tensor([[0.4885, 0.9907, 0.2911],
        [0.7310, 0.0848, 0.0046],
        [0.9029, 0.6800, 0.8854],
        [0.6106, 0.1693, 0.1537],
        [0.7217, 0.1609, 0.6773]])

In [25]:
a = torch.Tensor(2,4)
b = torch.Tensor(4,2)

c = torch.matmul(a,b)
c

tensor([[ 1.1660e+19, -3.9125e+11],
        [ 1.6581e+19,  3.3528e+22]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [ ]:
a.add_(1)
print(a)
print(b)

### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")