# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.1829e-23, 9.3607e-43, 6.3157e-24],
        [9.3607e-43, 1.1829e-23, 9.3607e-43],
        [1.1829e-23, 9.3607e-43, 2.0926e-22],
        [9.3607e-43, 8.0346e-24, 9.3607e-43],
        [3.8842e-24, 9.3607e-43, 1.2303e-22]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[2.3191e-01, 1.8119e-01, 4.5819e-01],
        [3.0177e-01, 3.5534e-01, 9.8247e-01],
        [6.4970e-01, 1.8190e-01, 6.3442e-01],
        [7.3433e-05, 3.5582e-01, 7.8660e-02],
        [3.2323e-03, 8.7147e-01, 8.2695e-01]])


Get its size

In [5]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [6]:
x[1:3] = 2
print(x)

tensor([[2.3191e-01, 1.8119e-01, 4.5819e-01],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        [2.0000e+00, 2.0000e+00, 2.0000e+00],
        [7.3433e-05, 3.5582e-01, 7.8660e-02],
        [3.2323e-03, 8.7147e-01, 8.2695e-01]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [37]:
x = torch.Tensor(2,17)
x.size()

torch.Size([2, 17])

In [8]:
x = torch.FloatTensor(3,1)
x.dtype

torch.float32

In [9]:
x = torch.LongTensor(5,2,1) # makes it li
x[:] = 7
x

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [10]:
x = torch.ByteTensor(5)
x[1:4] = 1
x

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [38]:
x = torch.rand(5, 3)
print(x)
y = torch.rand(5, 3)
print(x + y)

tensor([[0.2490, 0.4077, 0.6974],
        [0.1024, 0.1951, 0.3213],
        [0.5277, 0.9291, 0.2967],
        [0.1999, 0.2557, 0.1764],
        [0.0898, 0.5375, 0.0152]])
tensor([[0.5001, 1.1773, 1.5924],
        [0.5437, 1.1743, 0.9037],
        [0.9097, 1.8296, 0.8936],
        [0.5874, 0.6489, 0.8845],
        [0.7729, 0.7000, 0.9124]])


### 2.2 Addition: syntax 2

In [39]:
print(torch.add(x, y))

tensor([[0.5001, 1.1773, 1.5924],
        [0.5437, 1.1743, 0.9037],
        [0.9097, 1.8296, 0.8936],
        [0.5874, 0.6489, 0.8845],
        [0.7729, 0.7000, 0.9124]])


### 2.3 Addition: giving an output tensor

In [40]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.5001, 1.1773, 1.5924],
        [0.5437, 1.1743, 0.9037],
        [0.9097, 1.8296, 0.8936],
        [0.5874, 0.6489, 0.8845],
        [0.7729, 0.7000, 0.9124]])


### 2.4 Addition: in-place

adds `x`to `y`

In [41]:
y.add_(x)
print(y)

tensor([[0.5001, 1.1773, 1.5924],
        [0.5437, 1.1743, 0.9037],
        [0.9097, 1.8296, 0.8936],
        [0.5874, 0.6489, 0.8845],
        [0.7729, 0.7000, 0.9124]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [42]:
print(x[:, 1])

tensor([0.4077, 0.1951, 0.9291, 0.2557, 0.5375])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [43]:
torch.Tensor.mul(x,y)

tensor([[0.1245, 0.4800, 1.1106],
        [0.0557, 0.2291, 0.2903],
        [0.4801, 1.6999, 0.2652],
        [0.1174, 0.1659, 0.1560],
        [0.0694, 0.3762, 0.0139]])

In [44]:
x.mul_(y)

tensor([[0.1245, 0.4800, 1.1106],
        [0.0557, 0.2291, 0.2903],
        [0.4801, 1.6999, 0.2652],
        [0.1174, 0.1659, 0.1560],
        [0.0694, 0.3762, 0.0139]])

In [45]:
torch.Tensor.div(x,y)

tensor([[0.2490, 0.4077, 0.6974],
        [0.1024, 0.1951, 0.3213],
        [0.5277, 0.9291, 0.2967],
        [0.1999, 0.2557, 0.1764],
        [0.0898, 0.5375, 0.0152]])

In [17]:
a = torch.Tensor(2,4)
b = torch.Tensor(4,2)

c = torch.matmul(a,b)
c

tensor([[0.0000e+00, 0.0000e+00],
        [6.8981e+14, 5.3095e+11]])

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [31]:
import torch

In [35]:
x = torch.ones(5,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [33]:
x = x.cpu().numpy()
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [46]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.1245, 0.4800, 1.1106],
        [0.0557, 0.2291, 0.2903],
        [0.4801, 1.6999, 0.2652],
        [0.1174, 0.1659, 0.1560],
        [0.0694, 0.3762, 0.0139]], device='cuda:0')
tensor([[0.5001, 1.1773, 1.5924],
        [0.5437, 1.1743, 0.9037],
        [0.9097, 1.8296, 0.8936],
        [0.5874, 0.6489, 0.8845],
        [0.7729, 0.7000, 0.9124]], device='cuda:0')
tensor([[0.6246, 1.6573, 2.7030],
        [0.5994, 1.4035, 1.1940],
        [1.3897, 3.5295, 1.1588],
        [0.7048, 0.8148, 1.0405],
        [0.8423, 1.0762, 0.9263]], device='cuda:0')
